name: Linux CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Linux compilation
    steps:
      - uses: actions/checkout@v2
      - name: deps
        run: echo "deb-src http://cran.ms.unimelb.edu.au/bin/linux/ubuntu" >> /etc/apt/sources.list && sudo apt-get update && sudo apt-get build-dep glfw
      - name: build
        run: ./scripts/build.sh